fix: remove jquery usage at the module root scope (#941)
This caused an error `TypeError: $__default.default.extend is not a function` in some environments.